[project]
name = "hstu-seren"
version = "0.1.1"
description = "HSTU for serendipity recommendation"
authors = [{ name = "czy", email = "chenzhiyuan0920@gmail.com" }]
readme = "README.md"
keywords = ['python']
requires-python = ">=3.10"
dependencies = [
    # --------- pytorch / lightning --------- #
    "torch>=2.6.0",
    "torchvision>=0.20.0",
    "lightning>=2.4.0",
    "torchmetrics>=1.0.3",
    # --------- hydra / console --------- #
    "hydra-core>=1.3.2",
    "hydra-colorlog>=1.2.0",
    "rich>=13.7.1",
    # --------- merged deps (user snippet) --------- #
    "absl-py>=2.3.1",
    "cloudpickle>=3.1.1",
    "filelock>=3.13.1",
    "fsspec>=2024.6.1",
    "gin-config>=0.5.0",
    "grpcio>=1.74.0",
    "importlib-metadata>=8.7.0",
    "iopath>=0.1.10",
    "jinja2>=3.1.4",
    "lightning-utilities>=0.15.2",
    "markdown>=3.8.2",
    "markupsafe>=2.1.5",
    "mpmath>=1.3.0",
    "mypy-extensions>=1.1.0",
    "networkx>=3.3",
    "numpy>=2.1.2",
    "orjson>=3.11.2",
    "packaging>=25.0",
    "pandas>=2.3.1",
    "pillow>=11.3.0",
    "portalocker>=3.2.0",
    "protobuf>=6.32.0",
    "pybind11>=3.0.0",
    "pyre-extensions>=0.0.32",
    "python-dateutil>=2.9.0.post0",
    "pytz>=2025.2",
    "pyvers>=0.1.0",
    "setuptools>=70.2.0",
    "six>=1.17.0",
    "sympy>=1.13.1",
    "tensorboard>=2.20.0",
    "tensorboard-data-server>=0.7.2",
    "tensordict>=0.9.1",
    "tqdm>=4.67.1",
    "typing-extensions>=4.12.2",
    "typing-inspect>=0.9.0",
    "tzdata>=2025.2",
    "werkzeug>=3.1.3",
    "zipp>=3.23.0",
    "sentence-transformers",
    "transformers",
    "flash-attn<2.8.0",
    "pyarrow>=21.0.0",
]

[project.urls]
Homepage = "https://stellafull.github.io/hstu-seren/"
Repository = "https://github.com/stellafull/hstu-seren"
Documentation = "https://stellafull.github.io/hstu-seren/"

[project.optional-dependencies]
dev = [
    "ruff",
    "black",
    "pre-commit",
]

test = [
    "pytest",
    "coverage",
]

[tool.hatch.build.targets.wheel]
packages = ["src/generative_recommenders_pl"]

[tool.hatch.build.targets.editable]
packages = ["src/generative_recommenders_pl"]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
