_target_: generative_recommenders_pl.models.modeling.HSTUSeren

optimizer:
  _target_: torch.optim.AdamW
  _partial_: true
  lr: 0.0005
  betas: [0.9, 0.98]
  weight_decay: 0.01

scheduler:
  _target_: torch.optim.lr_scheduler.CosineAnnealingLR
  _partial_: true
  T_max: 100

configure_optimizer_params:
  monitor: val/ndcg@10
  interval: epoch
  frequency: 1

gr_output_length: 1
item_embedding_dim: 256
compile_model: false

embeddings:
  _target_: generative_recommenders_pl.models.embeddings.embeddings.LocalEmbeddingModule
  num_items: ${data.data_preprocessor.expected_max_item_id}
  item_embedding_dim: ${model.item_embedding_dim}

preprocessor:
  _target_: generative_recommenders_pl.models.preprocessors.LearnablePositionalEmbeddingInputFeaturesPreprocessor
  max_sequence_len: ${eval:${data.max_sequence_length} + ${model.gr_output_length} + 1}
  embedding_dim: ${model.item_embedding_dim}
  dropout_rate: 0.1

sequence_encoder:
  _target_: generative_recommenders_pl.models.sequential_encoders.hstu.HSTU
  max_sequence_len: ${data.max_sequence_length}
  max_output_len: ${eval:${model.gr_output_length} + 1}
  embedding_dim: ${model.item_embedding_dim}
  item_embedding_dim: ${model.item_embedding_dim}
  num_blocks: 2
  num_heads: 1
  attention_dim: ${model.item_embedding_dim}
  linear_dim: ${model.item_embedding_dim}
  linear_dropout_rate: 0.1
  attn_dropout_rate: 0.0
  normalization: rel_bias
  linear_config: uvqk
  linear_activation: silu
  concat_ua: false
  enable_relative_attention_bias: true

postprocessor:
  _target_: generative_recommenders_pl.models.postprocessors.postprocessors.L2NormEmbeddingPostprocessor
  embedding_dim: ${model.item_embedding_dim}
  eps: 1e-6

similarity: null
negatives_sampler: null
candidate_index: null

tie_weights: true
loss_weights: { rel: 1.0, ser: 1.0 }
pos_weight: 1.0
metrics:
  ranking:
    ks: [5, 10]
  serendipity:
    ks: [5, 10]
